### ISSUE TITLE
Zippy Media Import - Umbraco package

### ISSUE THREAD

**Issue by bjarnef** [Pumpin/ZippyMedia#1]
Hi..

I guess this project is for https://our.umbraco.org/projects/backoffice-extensions/zippy-media-import/ ?
Do you want to share the source code here?

If you want, then it would be great if you added the link to this repository for the Umbraco package source url.

A few comment:.
- the menu item + dialog header has a typo. it should "Unpack ZIP archive"
- the text of the green button should be "Upload and unpack"
- "Select the zip file u want to upload to Books": Change it to "Select the zip file you want to upload to Books" or "Select the zip file you want to upload and unpack to Books" (with the first one you might think it upload a zip file to Books).
- Consider to localize text (it is really cool with Umbraco 7.3.0 since you can include the translations in a  "lang" folder in your package folder. Then each language files are named like: da-DK.xml, en-GB.xml, en-US.xml etc.)

**Comment by Pumpin** [comment]
Hey Bjarne 

thanks for the heads up there is now a new package on nuget and our, that fixes the typos and makes the linking between nuget our and github more intuitive. 

As of now i am not using the localize text cause it seems to break the compatibility with version 7.2

**Comment by bjarnef** [comment]
Well for pre Umbraco 7.3, the language keys needed to be in the core language files in /Umbraco/Config/Lang/ folder.

If installing the package for Umbraco 7.0-7.2 they could manually merge the keys from /App_Plugins/ZippyMedia/Lang/{culture}.xml files..

The AngularJS part works the same way:
<localize key="area_key"></localize>

E.g.

```
<area alias=="zippyMedia">
      <key alias="filesToUploadAndUnpack">File to upload and unpack</key>
</area>
```

```
<area alias=="zippyMedia">
      <key alias="filesToUploadAndUnpack">Filer til upload og udpakning</key>
</area>
```

But in the .NET code it have been using ui.Text until the new TextService now is available: https://twitter.com/Shazwazza/status/613986522631667712

and that will break compatibility with version 7.2.

maybe take a look at how Merchello use it https://github.com/Merchello/Merchello/blob/c252625d56d0966d3d274a5fac3550b6359c9b37/src/Merchello.Web/Trees/MerchelloTreeController.cs

I think you could check against Umbraco and fallback to ui.Text ..
